import type { Metadata } from 'next'
import './globals.css'
import ButtonWhatsap from '@/shared/ui/ButtonWhatsap'
import NavbarContainer from '@/shared/components/nav/NavbarContainer'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className="font-sans w-full min-h-screen scroll-smooth antialiased"
                cz-shortcut-listen="true"
            >
                <header className="sticky w-full top-0 z-50 ">
                    <NavbarContainer />
                </header>
                <main className="w-full min-h-screen scroll-smooth ">
                    {children} <ButtonWhatsap />
                </main>
                <div id="modals-root"></div>
            </body>
        </html>
    )
}
