import type { Metadata } from 'next'
import { Geist, Geist_Mono, Questrial } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const questrial = Questrial({
    variable: '--font-questrial',
    subsets: ['latin'],
    weight: '400',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${questrial.variable} `}
                cz-shortcut-listen="true"
            >
                {children}
            </body>
        </html>
    )
}
